[package]
name = "scrap-native"
description = "Scrap Native"
authors = ["Tomáš Wróbel <mail@tomaswrobel.dev>"]
edition = "2021"
publish = false
version = "0.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "scrap_native_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
tauri = { version = "2.1.1", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
swc_core = { version = "6.0.2", features = [
	"ecma_parser",
	"ecma_ast",
	"common",
	"ecma_visit",
	"ecma_ast_serde",
	"ecma_transforms",
	"ecma_transforms_typescript",
] }
swc = "9.0.0"
anyhow = "1.0.92"
tauri-plugin-fs = "2.0.3"
tauri-plugin-dialog = "2.0.3"
