name: "Release"

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            targets:
              - aarch64-apple-darwin
              - x86_64-apple-darwin
            args: "--target universal-apple-darwin"

          - platform: "ubuntu-24.04"
            targets: []
            args: ""

          - platform: "windows-latest"
            targets: []
            args: ""

    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.82.0
        with:
          targets: ${{ join(matrix.targets, ',') }}

      - name: Install dependencies on Ubuntu
        if: matrix.platform == 'ubuntu-24.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install front-end dependencies
        run: pnpm install

      - name: Create release body
        id: changelog
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "" >> "$GITHUB_OUTPUT"
          echo "Introducing Scrap, a revolutionary visual programming editor designed for creators of all levels." >> "$GITHUB_OUTPUT"
          echo "Much like Scratch, Scrap provides an intuitive interface for building interactive projects through " >> "$GITHUB_OUTPUT"
          echo "block-based coding. However, Scrap takes it a step further by seamlessly integrating TypeScript, " >> "$GITHUB_OUTPUT"
          echo "empowering users to leverage the flexibility and power of a full-fledged programming language. " >> "$GITHUB_OUTPUT"
          echo "Whether you're a beginner exploring the basics of coding or an experienced developer seeking " >> "$GITHUB_OUTPUT"
          echo "a more accessible way to prototype ideas, Scrap is your ultimate tool for bringing creativity " >> "$GITHUB_OUTPUT"
          echo "to life." >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          echo "Download Scrap today and start building your next project!" >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          echo "# Changelog" >> "$GITHUB_OUTPUT"
          echo "" >> "$GITHUB_OUTPUT"
          node --experimental-transform-types src/changelog.ts
          echo "" >> "$GITHUB_OUTPUT"
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate icons
        run: pnpm tauri icon src/assets/icon.svg --ios-color "#199950"

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "Scrap v__VERSION__"
          releaseBody: ${{ steps.changelog.outputs.body }}
          args: ${{ matrix.args }}
